replicaCount: 2

extraEnv:
  - name: APP_ENV
    value: staging

resources:
  limits:
    cpu: 400m
    memory: 384Mi
  requests:
    cpu: 75m
    memory: 96Mi

service:
  type: LoadBalancer

ingress:
  enabled: false
  className: nginx
  hosts: []

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
